In [3]:
!pip install numpy
import numpy as np


In [4]:
python_list = [1,2,3,4,5]
print(python_list)
numpy_array = np.array([1,2,3,4,5])
print(numpy_array)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [5]:
arr=np.array([1,2,6,5,8,6,5])
print(arr)

[1 2 6 5 8 6 5]


In [9]:
zeroes = np.array(3*3)
print(zeroes)

9


In [15]:
zeroes = np.zeros(3)
print(zeroes)

[0. 0. 0.]


In [17]:
print(np.full((2,3),7))

[[7 7 7]
 [7 7 7]]


In [18]:
zeroes = np.arange(1,10,2)
print(zeroes)

[1 3 5 7 9]


In [20]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
numpy_array = np.array([[1,2,3,4,5])
print(numpy_array.shape)

(5,)


In [27]:
numpy_array = np.array([1,2,3,4,5,5555])
print(numpy_array.size)

6


In [29]:
numpy_array = np.array([1,2,3,4,5,5555])
print(numpy_array.ndim)

1


In [30]:
numpy_array = np.array([1,2,3,4,5,5555])
print(numpy_array.dtype)

int64


In [32]:
numpy_array = np.array([1.7,2.5,3.9,4.1,5.3,5.6])
print(numpy_array.astype(int))

[1 2 3 4 5 5]


In [34]:
arr = np.array([1.7,2.5,3.9,4.1,5.3,5.6])
print(arr +5)
print(arr -5)
print(arr **5)
print(arr /5)
print(arr //5)
print(arr %5)

[ 6.7  7.5  8.9  9.1 10.3 10.6]
[-3.3 -2.5 -1.1 -0.9  0.3  0.6]
[  14.19857   97.65625  902.24199 1158.56201 4181.95493 5507.31776]
[0.34 0.5  0.78 0.82 1.06 1.12]
[0. 0. 0. 0. 1. 1.]
[1.7 2.5 3.9 4.1 0.3 0.6]


In [35]:
arr = np.array([1.7,2.5,3.9,4.1,5.3,5.6])
print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))
print(np.var(arr))

23.1
3.85
1.7
5.6
1.3949313005783952
1.945833333333333


In [3]:
import numpy as np
arr =np.array([10,20,30,40,50])
print(arr[0])
print(arr[-1])

10
50


In [5]:
arr =np.array([10,20,30,40,50])
print(arr[[0, 2, 4]])

[10 30 50]


In [6]:
arr =np.array([10,20,30,40,50])
print(arr[arr>25])

[30 40 50]


In [9]:
arr =np.array([10,20,30,40,50,6])
reshape_arr= arr.reshape(2,3)
print(reshape_arr)

[[10 20 30]
 [40 50  6]]


In [12]:
arr=np.array([[1,2,3], [5,6,8]])
print(arr)

[[1 2 3]
 [5 6 8]]


In [13]:
arr=np.array([[1,2,3], [5,6,8]])
print(arr.ravel())
print(arr.flatten())

[1 2 3 5 6 8]
[1 2 3 5 6 8]


In [4]:
import numpy as np
arr =np.array([10,20,30,40,50,6])
new=np.insert(arr, 2, 100, axis=0)
print(new)

[ 10  20 100  30  40  50   6]


In [6]:
arr=np.array([[1,2,3], [5,6,8]])
new=np.insert(arr, 1, [7,8,9], axis=0)
print(new)

[[1 2 3]
 [7 8 9]
 [5 6 8]]


In [8]:
arr=np.array([[1,2,3], [5,6,8]])
new=np.insert(arr, 1, [7,8], axis=1)
print(new)

[[1 7 2 3]
 [5 8 6 8]]


In [9]:
arr=np.array([[1,2,3], [5,6,8]])
new=np.insert(arr, 1, [7,8], axis=None)
print(new)

[1 7 8 2 3 5 6 8]


In [10]:
arr =np.array([10,20,30,40,50,6])
new=np.append(arr,[50,60,90,90])
print(new)

[10 20 30 40 50  6 50 60 90 90]


In [14]:
arr1 =np.array([10,20,30,40,50,6])
arr2 =np.array([50,60,90,90])
add_arr =np.concatenate((arr1, arr2), axis=0)
print(add_arr)

[10 20 30 40 50  6 50 60 90 90]


In [18]:
arr1 =np.array([[10,20,30], [1,2,5]])
arr2 =np.array([[50,60,90], [2,5,6]])
add_arr =np.concatenate((arr1, arr2), axis=1)
print(add_arr)

[[10 20 30 50 60 90]
 [ 1  2  5  2  5  6]]


In [19]:
arr1 =np.array([10,20,30,40,50,6])
new= np.delete(arr1, 1, axis=None)
print(new)

[10 30 40 50  6]


In [21]:
arr1 =np.array([[10,20,30], [1,2,5]])
arr2 =np.array([[50,60,90], [2,5,6]])
print(np.vstack((arr1, arr2)))
print(np.hstack((arr1, arr2)))

[[10 20 30]
 [ 1  2  5]
 [50 60 90]
 [ 2  5  6]]
[[10 20 30 50 60 90]
 [ 1  2  5  2  5  6]]


In [22]:
arr1 =np.array([10,20,30,40,50,6])
print(np.split(arr1, 2)) 

[array([10, 20, 30]), array([40, 50,  6])]


In [1]:
import numpy as np

In [2]:
arr1 =np.array([10,20,30,40,50,6])
discount = 10
finalprice= arr1-(arr1*discount/100)
print(finalprice)

[ 9.  18.  27.  36.  45.   5.4]


In [3]:
arr=np.array([10,20,30,40,50,6])
result =arr*2
print(result)

[ 20  40  60  80 100  12]


In [4]:
arr1 =np.array([[10,20,30], [1,2,5]])
arr2 =np.array([50,60,90])
result = arr1 + arr2
print(result)

[[ 60  80 120]
 [ 51  62  95]]


In [ ]:
# arr1 =np.array([[10,20,30], [1,2,5]])  #2,3
# arr2 =np.array([5,6])
# #error
# .reshape() can fix it


In [5]:
arr1 =np.array([10,20])
arr2 =np.array([5,6])
result=arr1+arr2
print(result)

[15 26]


In [6]:
arr1 =np.array([10,20])
arr2 =np.array([5,6])
result=arr1*20
print(result)

[200 400]


In [10]:
arr1 =np.array([10,20,np.nan, 4, np.nan, 6])
print(np.isnan(arr1))

[False False  True False  True False]


In [11]:
arr1 =np.array([10,20,np.nan, 4, np.nan, 6])
arr2=np.nan_to_num(arr,nan=12)
print(arr2)

[10 20 30 40 50  6]


In [13]:
arr1 =np.array([10,20,np.nan, 4, np.nan, 6])
# arr2=np.nan_to_num(arr,nan=12)
print(np.isinf(arr1))

[False False False False False False]


In [14]:
arr1 =np.array([10,20,np.inf, 4, -np.inf, 6])
# arr2=np.nan_to_num(arr,nan=12)
print(np.isinf(arr1))

[False False  True False  True False]


In [15]:
arr1 =np.array([10,20,np.inf, 4, -np.inf, 6])
# arr2=np.nan_to_num(arr,nan=12)
print(np.isinf(arr1))
arrr=np.nan_to_num(arr,posinf=100,neginf=1000)
print(arrr)

[False False  True False  True False]
[10 20 30 40 50  6]
